#!/bin/bash

echo "🔧 Fixing Vercel Auto-Deployment Issues..."
echo ""

echo "📋 Steps to fix automatic deployments:"
echo ""
echo "1. Go to https://vercel.com/dashboard"
echo "2. Click on your project (hidden-coffee-gt-website)"
echo "3. Go to Settings > Git"
echo "4. Check if GitHub is connected"
echo "5. If not connected, click 'Connect Git Repository'"
echo "6. Select your GitHub repo: YuyenMarcus/hidden-coffee-gt-website"
echo "7. Set Production Branch to 'main'"
echo "8. Save settings"
echo ""
echo "🔍 Alternative: Check these settings:"
echo "- Build Command: npm run build"
echo "- Output Directory: .next"
echo "- Install Command: npm install"
echo "- Root Directory: ./ (leave empty)"
echo ""
echo "🚀 After fixing, test with:"
echo "git commit --allow-empty -m 'Test auto-deploy' && git push origin main"
echo ""
echo "✅ Vercel should automatically deploy within 1-2 minutes" 